// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: proto/tinyurl.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// URL shortening messages
type ShortenURLRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShortenURLRequest) Reset() {
	*x = ShortenURLRequest{}
	mi := &file_proto_tinyurl_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShortenURLRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShortenURLRequest) ProtoMessage() {}

func (x *ShortenURLRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tinyurl_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShortenURLRequest.ProtoReflect.Descriptor instead.
func (*ShortenURLRequest) Descriptor() ([]byte, []int) {
	return file_proto_tinyurl_proto_rawDescGZIP(), []int{0}
}

func (x *ShortenURLRequest) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *ShortenURLRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

type ShortenURLResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Shortenurl    string                 `protobuf:"bytes,2,opt,name=shortenurl,proto3" json:"shortenurl,omitempty"`
	Originalurl   string                 `protobuf:"bytes,3,opt,name=originalurl,proto3" json:"originalurl,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShortenURLResponse) Reset() {
	*x = ShortenURLResponse{}
	mi := &file_proto_tinyurl_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShortenURLResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShortenURLResponse) ProtoMessage() {}

func (x *ShortenURLResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tinyurl_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShortenURLResponse.ProtoReflect.Descriptor instead.
func (*ShortenURLResponse) Descriptor() ([]byte, []int) {
	return file_proto_tinyurl_proto_rawDescGZIP(), []int{1}
}

func (x *ShortenURLResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ShortenURLResponse) GetShortenurl() string {
	if x != nil {
		return x.Shortenurl
	}
	return ""
}

func (x *ShortenURLResponse) GetOriginalurl() string {
	if x != nil {
		return x.Originalurl
	}
	return ""
}

type ExtendURLRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExtendURLRequest) Reset() {
	*x = ExtendURLRequest{}
	mi := &file_proto_tinyurl_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExtendURLRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExtendURLRequest) ProtoMessage() {}

func (x *ExtendURLRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tinyurl_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExtendURLRequest.ProtoReflect.Descriptor instead.
func (*ExtendURLRequest) Descriptor() ([]byte, []int) {
	return file_proto_tinyurl_proto_rawDescGZIP(), []int{2}
}

func (x *ExtendURLRequest) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *ExtendURLRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

type ExtendURLResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Originalurl   string                 `protobuf:"bytes,2,opt,name=originalurl,proto3" json:"originalurl,omitempty"`
	Extenedurl    string                 `protobuf:"bytes,3,opt,name=extenedurl,proto3" json:"extenedurl,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExtendURLResponse) Reset() {
	*x = ExtendURLResponse{}
	mi := &file_proto_tinyurl_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExtendURLResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExtendURLResponse) ProtoMessage() {}

func (x *ExtendURLResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tinyurl_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExtendURLResponse.ProtoReflect.Descriptor instead.
func (*ExtendURLResponse) Descriptor() ([]byte, []int) {
	return file_proto_tinyurl_proto_rawDescGZIP(), []int{3}
}

func (x *ExtendURLResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ExtendURLResponse) GetOriginalurl() string {
	if x != nil {
		return x.Originalurl
	}
	return ""
}

func (x *ExtendURLResponse) GetExtenedurl() string {
	if x != nil {
		return x.Extenedurl
	}
	return ""
}

// User management messages
type RegisterUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	FirstName     string                 `protobuf:"bytes,3,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName      string                 `protobuf:"bytes,4,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterUserRequest) Reset() {
	*x = RegisterUserRequest{}
	mi := &file_proto_tinyurl_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterUserRequest) ProtoMessage() {}

func (x *RegisterUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tinyurl_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterUserRequest.ProtoReflect.Descriptor instead.
func (*RegisterUserRequest) Descriptor() ([]byte, []int) {
	return file_proto_tinyurl_proto_rawDescGZIP(), []int{4}
}

func (x *RegisterUserRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *RegisterUserRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *RegisterUserRequest) GetFirstName() string {
	if x != nil {
		return x.FirstName
	}
	return ""
}

func (x *RegisterUserRequest) GetLastName() string {
	if x != nil {
		return x.LastName
	}
	return ""
}

type RegisterUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	FirstName     string                 `protobuf:"bytes,3,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName      string                 `protobuf:"bytes,4,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterUserResponse) Reset() {
	*x = RegisterUserResponse{}
	mi := &file_proto_tinyurl_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterUserResponse) ProtoMessage() {}

func (x *RegisterUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tinyurl_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterUserResponse.ProtoReflect.Descriptor instead.
func (*RegisterUserResponse) Descriptor() ([]byte, []int) {
	return file_proto_tinyurl_proto_rawDescGZIP(), []int{5}
}

func (x *RegisterUserResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *RegisterUserResponse) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *RegisterUserResponse) GetFirstName() string {
	if x != nil {
		return x.FirstName
	}
	return ""
}

func (x *RegisterUserResponse) GetLastName() string {
	if x != nil {
		return x.LastName
	}
	return ""
}

type LoginRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginRequest) Reset() {
	*x = LoginRequest{}
	mi := &file_proto_tinyurl_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginRequest) ProtoMessage() {}

func (x *LoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tinyurl_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginRequest.ProtoReflect.Descriptor instead.
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return file_proto_tinyurl_proto_rawDescGZIP(), []int{6}
}

func (x *LoginRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *LoginRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type LoginResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	User          *RegisterUserRequest   `protobuf:"bytes,2,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginResponse) Reset() {
	*x = LoginResponse{}
	mi := &file_proto_tinyurl_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginResponse) ProtoMessage() {}

func (x *LoginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tinyurl_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginResponse.ProtoReflect.Descriptor instead.
func (*LoginResponse) Descriptor() ([]byte, []int) {
	return file_proto_tinyurl_proto_rawDescGZIP(), []int{7}
}

func (x *LoginResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *LoginResponse) GetUser() *RegisterUserRequest {
	if x != nil {
		return x.User
	}
	return nil
}

var File_proto_tinyurl_proto protoreflect.FileDescriptor

const file_proto_tinyurl_proto_rawDesc = "" +
	"\n" +
	"\x13proto/tinyurl.proto\x12\x05proto\"A\n" +
	"\x11ShortenURLRequest\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\"n\n" +
	"\x12ShortenURLResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x1e\n" +
	"\n" +
	"shortenurl\x18\x02 \x01(\tR\n" +
	"shortenurl\x12 \n" +
	"\voriginalurl\x18\x03 \x01(\tR\voriginalurl\"@\n" +
	"\x10ExtendURLRequest\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\"m\n" +
	"\x11ExtendURLResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12 \n" +
	"\voriginalurl\x18\x02 \x01(\tR\voriginalurl\x12\x1e\n" +
	"\n" +
	"extenedurl\x18\x03 \x01(\tR\n" +
	"extenedurl\"\x89\x01\n" +
	"\x13RegisterUserRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\x12\x1d\n" +
	"\n" +
	"first_name\x18\x03 \x01(\tR\tfirstName\x12\x1b\n" +
	"\tlast_name\x18\x04 \x01(\tR\blastName\"\x86\x01\n" +
	"\x14RegisterUserResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12\x1d\n" +
	"\n" +
	"first_name\x18\x03 \x01(\tR\tfirstName\x12\x1b\n" +
	"\tlast_name\x18\x04 \x01(\tR\blastName\"F\n" +
	"\fLoginRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"W\n" +
	"\rLoginResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12.\n" +
	"\x04user\x18\x02 \x01(\v2\x1a.proto.RegisterUserRequestR\x04user2\x98\x02\n" +
	"\x0eTinyURLService\x12C\n" +
	"\n" +
	"ShortenURL\x12\x18.proto.ShortenURLRequest\x1a\x19.proto.ShortenURLResponse\"\x00\x12@\n" +
	"\tExtendURL\x12\x17.proto.ExtendURLRequest\x1a\x18.proto.ExtendURLResponse\"\x00\x12I\n" +
	"\fRegisterUser\x12\x1a.proto.RegisterUserRequest\x1a\x1b.proto.RegisterUserResponse\"\x00\x124\n" +
	"\x05Login\x12\x13.proto.LoginRequest\x1a\x14.proto.LoginResponse\"\x00B\x1aZ\x18TinyURL_Refactored/protob\x06proto3"

var (
	file_proto_tinyurl_proto_rawDescOnce sync.Once
	file_proto_tinyurl_proto_rawDescData []byte
)

func file_proto_tinyurl_proto_rawDescGZIP() []byte {
	file_proto_tinyurl_proto_rawDescOnce.Do(func() {
		file_proto_tinyurl_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_tinyurl_proto_rawDesc), len(file_proto_tinyurl_proto_rawDesc)))
	})
	return file_proto_tinyurl_proto_rawDescData
}

var file_proto_tinyurl_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_proto_tinyurl_proto_goTypes = []any{
	(*ShortenURLRequest)(nil),    // 0: proto.ShortenURLRequest
	(*ShortenURLResponse)(nil),   // 1: proto.ShortenURLResponse
	(*ExtendURLRequest)(nil),     // 2: proto.ExtendURLRequest
	(*ExtendURLResponse)(nil),    // 3: proto.ExtendURLResponse
	(*RegisterUserRequest)(nil),  // 4: proto.RegisterUserRequest
	(*RegisterUserResponse)(nil), // 5: proto.RegisterUserResponse
	(*LoginRequest)(nil),         // 6: proto.LoginRequest
	(*LoginResponse)(nil),        // 7: proto.LoginResponse
}
var file_proto_tinyurl_proto_depIdxs = []int32{
	4, // 0: proto.LoginResponse.user:type_name -> proto.RegisterUserRequest
	0, // 1: proto.TinyURLService.ShortenURL:input_type -> proto.ShortenURLRequest
	2, // 2: proto.TinyURLService.ExtendURL:input_type -> proto.ExtendURLRequest
	4, // 3: proto.TinyURLService.RegisterUser:input_type -> proto.RegisterUserRequest
	6, // 4: proto.TinyURLService.Login:input_type -> proto.LoginRequest
	1, // 5: proto.TinyURLService.ShortenURL:output_type -> proto.ShortenURLResponse
	3, // 6: proto.TinyURLService.ExtendURL:output_type -> proto.ExtendURLResponse
	5, // 7: proto.TinyURLService.RegisterUser:output_type -> proto.RegisterUserResponse
	7, // 8: proto.TinyURLService.Login:output_type -> proto.LoginResponse
	5, // [5:9] is the sub-list for method output_type
	1, // [1:5] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_tinyurl_proto_init() }
func file_proto_tinyurl_proto_init() {
	if File_proto_tinyurl_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_tinyurl_proto_rawDesc), len(file_proto_tinyurl_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_tinyurl_proto_goTypes,
		DependencyIndexes: file_proto_tinyurl_proto_depIdxs,
		MessageInfos:      file_proto_tinyurl_proto_msgTypes,
	}.Build()
	File_proto_tinyurl_proto = out.File
	file_proto_tinyurl_proto_goTypes = nil
	file_proto_tinyurl_proto_depIdxs = nil
}
