// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: proto/tinyurl.proto

package proto

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Register User Request body
type RegisterUserRequest struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	FirstName string                 `protobuf:"bytes,1,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName  string                 `protobuf:"bytes,2,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	// Username should be constructed from first half of first_name and last half of last_name
	Username      string `protobuf:"bytes,3,opt,name=username,proto3" json:"username,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterUserRequest) Reset() {
	*x = RegisterUserRequest{}
	mi := &file_proto_tinyurl_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterUserRequest) ProtoMessage() {}

func (x *RegisterUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tinyurl_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterUserRequest.ProtoReflect.Descriptor instead.
func (*RegisterUserRequest) Descriptor() ([]byte, []int) {
	return file_proto_tinyurl_proto_rawDescGZIP(), []int{0}
}

func (x *RegisterUserRequest) GetFirstName() string {
	if x != nil {
		return x.FirstName
	}
	return ""
}

func (x *RegisterUserRequest) GetLastName() string {
	if x != nil {
		return x.LastName
	}
	return ""
}

func (x *RegisterUserRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

// Registered User response body
type RegisteredUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisteredUserResponse) Reset() {
	*x = RegisteredUserResponse{}
	mi := &file_proto_tinyurl_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisteredUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisteredUserResponse) ProtoMessage() {}

func (x *RegisteredUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tinyurl_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisteredUserResponse.ProtoReflect.Descriptor instead.
func (*RegisteredUserResponse) Descriptor() ([]byte, []int) {
	return file_proto_tinyurl_proto_rawDescGZIP(), []int{1}
}

func (x *RegisteredUserResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *RegisteredUserResponse) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

// Request Params require for logging in
type LoginRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginRequest) Reset() {
	*x = LoginRequest{}
	mi := &file_proto_tinyurl_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginRequest) ProtoMessage() {}

func (x *LoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tinyurl_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginRequest.ProtoReflect.Descriptor instead.
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return file_proto_tinyurl_proto_rawDescGZIP(), []int{2}
}

func (x *LoginRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

// Response body after logging in
type LoginResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	User          *RegisterUserRequest   `protobuf:"bytes,2,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginResponse) Reset() {
	*x = LoginResponse{}
	mi := &file_proto_tinyurl_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginResponse) ProtoMessage() {}

func (x *LoginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tinyurl_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginResponse.ProtoReflect.Descriptor instead.
func (*LoginResponse) Descriptor() ([]byte, []int) {
	return file_proto_tinyurl_proto_rawDescGZIP(), []int{3}
}

func (x *LoginResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *LoginResponse) GetUser() *RegisterUserRequest {
	if x != nil {
		return x.User
	}
	return nil
}

// Shortening URL
type ShortenURLRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Url           string                 `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShortenURLRequest) Reset() {
	*x = ShortenURLRequest{}
	mi := &file_proto_tinyurl_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShortenURLRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShortenURLRequest) ProtoMessage() {}

func (x *ShortenURLRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tinyurl_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShortenURLRequest.ProtoReflect.Descriptor instead.
func (*ShortenURLRequest) Descriptor() ([]byte, []int) {
	return file_proto_tinyurl_proto_rawDescGZIP(), []int{4}
}

func (x *ShortenURLRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *ShortenURLRequest) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

// Shortening URL
type ShortenURLResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Shortenurl    string                 `protobuf:"bytes,2,opt,name=shortenurl,proto3" json:"shortenurl,omitempty"`
	Originalurl   string                 `protobuf:"bytes,3,opt,name=originalurl,proto3" json:"originalurl,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShortenURLResponse) Reset() {
	*x = ShortenURLResponse{}
	mi := &file_proto_tinyurl_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShortenURLResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShortenURLResponse) ProtoMessage() {}

func (x *ShortenURLResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tinyurl_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShortenURLResponse.ProtoReflect.Descriptor instead.
func (*ShortenURLResponse) Descriptor() ([]byte, []int) {
	return file_proto_tinyurl_proto_rawDescGZIP(), []int{5}
}

func (x *ShortenURLResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ShortenURLResponse) GetShortenurl() string {
	if x != nil {
		return x.Shortenurl
	}
	return ""
}

func (x *ShortenURLResponse) GetOriginalurl() string {
	if x != nil {
		return x.Originalurl
	}
	return ""
}

// Extended URL
type ExtendURLRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Url           string                 `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExtendURLRequest) Reset() {
	*x = ExtendURLRequest{}
	mi := &file_proto_tinyurl_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExtendURLRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExtendURLRequest) ProtoMessage() {}

func (x *ExtendURLRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tinyurl_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExtendURLRequest.ProtoReflect.Descriptor instead.
func (*ExtendURLRequest) Descriptor() ([]byte, []int) {
	return file_proto_tinyurl_proto_rawDescGZIP(), []int{6}
}

func (x *ExtendURLRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *ExtendURLRequest) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

// Extended URL
type ExtendURLResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Originalurl   string                 `protobuf:"bytes,2,opt,name=originalurl,proto3" json:"originalurl,omitempty"`
	Extenedurl    string                 `protobuf:"bytes,3,opt,name=extenedurl,proto3" json:"extenedurl,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExtendURLResponse) Reset() {
	*x = ExtendURLResponse{}
	mi := &file_proto_tinyurl_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExtendURLResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExtendURLResponse) ProtoMessage() {}

func (x *ExtendURLResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tinyurl_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExtendURLResponse.ProtoReflect.Descriptor instead.
func (*ExtendURLResponse) Descriptor() ([]byte, []int) {
	return file_proto_tinyurl_proto_rawDescGZIP(), []int{7}
}

func (x *ExtendURLResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ExtendURLResponse) GetOriginalurl() string {
	if x != nil {
		return x.Originalurl
	}
	return ""
}

func (x *ExtendURLResponse) GetExtenedurl() string {
	if x != nil {
		return x.Extenedurl
	}
	return ""
}

var File_proto_tinyurl_proto protoreflect.FileDescriptor

const file_proto_tinyurl_proto_rawDesc = "" +
	"\n" +
	"\x13proto/tinyurl.proto\x12\atinyurl\x1a\x1cgoogle/api/annotations.proto\"m\n" +
	"\x13RegisterUserRequest\x12\x1d\n" +
	"\n" +
	"first_name\x18\x01 \x01(\tR\tfirstName\x12\x1b\n" +
	"\tlast_name\x18\x02 \x01(\tR\blastName\x12\x1a\n" +
	"\busername\x18\x03 \x01(\tR\busername\"L\n" +
	"\x16RegisteredUserResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\"*\n" +
	"\fLoginRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\"Y\n" +
	"\rLoginResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x120\n" +
	"\x04user\x18\x02 \x01(\v2\x1c.tinyurl.RegisterUserRequestR\x04user\"A\n" +
	"\x11ShortenURLRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x10\n" +
	"\x03url\x18\x02 \x01(\tR\x03url\"n\n" +
	"\x12ShortenURLResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x1e\n" +
	"\n" +
	"shortenurl\x18\x02 \x01(\tR\n" +
	"shortenurl\x12 \n" +
	"\voriginalurl\x18\x03 \x01(\tR\voriginalurl\"@\n" +
	"\x10ExtendURLRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x10\n" +
	"\x03url\x18\x02 \x01(\tR\x03url\"m\n" +
	"\x11ExtendURLResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12 \n" +
	"\voriginalurl\x18\x02 \x01(\tR\voriginalurl\x12\x1e\n" +
	"\n" +
	"extenedurl\x18\x03 \x01(\tR\n" +
	"extenedurl2\\\n" +
	"\fLoginService\x12L\n" +
	"\x05login\x12\x15.tinyurl.LoginRequest\x1a\x16.tinyurl.LoginResponse\"\x14\x82\xd3\xe4\x93\x02\x0e:\x01*\"\t/v1/login2n\n" +
	"\n" +
	"ShortenURL\x12`\n" +
	"\n" +
	"shortenurl\x12\x1a.tinyurl.ShortenURLRequest\x1a\x1b.tinyurl.ShortenURLResponse\"\x19\x82\xd3\xe4\x93\x02\x13:\x01*\"\x0e/v1/shortenurl2z\n" +
	"\fRegisterUser\x12j\n" +
	"\fregisterUser\x12\x1c.tinyurl.RegisterUserRequest\x1a\x1f.tinyurl.RegisteredUserResponse\"\x1b\x82\xd3\xe4\x93\x02\x15:\x01*\"\x10/v1/registeruser2k\n" +
	"\vExtendedURL\x12\\\n" +
	"\textendURL\x12\x19.tinyurl.ExtendURLRequest\x1a\x1a.tinyurl.ExtendURLResponse\"\x18\x82\xd3\xe4\x93\x02\x12:\x01*\"\r/v1/extendurlB:Z8github.com/gaurav.chaudhary/GolandProjects/TinyURL;protob\x06proto3"

var (
	file_proto_tinyurl_proto_rawDescOnce sync.Once
	file_proto_tinyurl_proto_rawDescData []byte
)

func file_proto_tinyurl_proto_rawDescGZIP() []byte {
	file_proto_tinyurl_proto_rawDescOnce.Do(func() {
		file_proto_tinyurl_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_tinyurl_proto_rawDesc), len(file_proto_tinyurl_proto_rawDesc)))
	})
	return file_proto_tinyurl_proto_rawDescData
}

var file_proto_tinyurl_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_proto_tinyurl_proto_goTypes = []any{
	(*RegisterUserRequest)(nil),    // 0: tinyurl.RegisterUserRequest
	(*RegisteredUserResponse)(nil), // 1: tinyurl.RegisteredUserResponse
	(*LoginRequest)(nil),           // 2: tinyurl.LoginRequest
	(*LoginResponse)(nil),          // 3: tinyurl.LoginResponse
	(*ShortenURLRequest)(nil),      // 4: tinyurl.ShortenURLRequest
	(*ShortenURLResponse)(nil),     // 5: tinyurl.ShortenURLResponse
	(*ExtendURLRequest)(nil),       // 6: tinyurl.ExtendURLRequest
	(*ExtendURLResponse)(nil),      // 7: tinyurl.ExtendURLResponse
}
var file_proto_tinyurl_proto_depIdxs = []int32{
	0, // 0: tinyurl.LoginResponse.user:type_name -> tinyurl.RegisterUserRequest
	2, // 1: tinyurl.LoginService.login:input_type -> tinyurl.LoginRequest
	4, // 2: tinyurl.ShortenURL.shortenurl:input_type -> tinyurl.ShortenURLRequest
	0, // 3: tinyurl.RegisterUser.registerUser:input_type -> tinyurl.RegisterUserRequest
	6, // 4: tinyurl.ExtendedURL.extendURL:input_type -> tinyurl.ExtendURLRequest
	3, // 5: tinyurl.LoginService.login:output_type -> tinyurl.LoginResponse
	5, // 6: tinyurl.ShortenURL.shortenurl:output_type -> tinyurl.ShortenURLResponse
	1, // 7: tinyurl.RegisterUser.registerUser:output_type -> tinyurl.RegisteredUserResponse
	7, // 8: tinyurl.ExtendedURL.extendURL:output_type -> tinyurl.ExtendURLResponse
	5, // [5:9] is the sub-list for method output_type
	1, // [1:5] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_tinyurl_proto_init() }
func file_proto_tinyurl_proto_init() {
	if File_proto_tinyurl_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_tinyurl_proto_rawDesc), len(file_proto_tinyurl_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   4,
		},
		GoTypes:           file_proto_tinyurl_proto_goTypes,
		DependencyIndexes: file_proto_tinyurl_proto_depIdxs,
		MessageInfos:      file_proto_tinyurl_proto_msgTypes,
	}.Build()
	File_proto_tinyurl_proto = out.File
	file_proto_tinyurl_proto_goTypes = nil
	file_proto_tinyurl_proto_depIdxs = nil
}
